[project]
authors = ["Hiran Wijesinghe <wwijesing1@bnl.gov>"]
channels = ["conda-forge"]
name = "test-redis-ws"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
serve = "python server.py"

[dependencies]
redis-py = "*"
fastapi = "*"
numpy = "*"
pydantic-settings = "*"
pydantic = "*"
httpx = "*"
uvicorn = "*"
msgpack-python = "*"