[project]
authors = ["Hiran Wijesinghe <wwijesing1@bnl.gov>"]
channels = ["conda-forge"]
name = "test-redis-ws"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[tasks]
serve = "python server.py"
stream = "python streaming_client.py"
write = "python writing_client.py"
test = "pytest tests/"

[dependencies]
redis-py = "*"
fastapi = "*"
numpy = "*"
pydantic-settings = "*"
pydantic = "*"
httpx = "*"
uvicorn = "*"
httpx-ws = "*"
locust = "*"
ruff = "*"
pytest = "*"

[pypi-dependencies]
msgpack = "*"
locust-plugins = {extras = ["websocket"], version = "*"}
